version: '3.8'

services:
  db:
    image: mariadb:latest
    env_file:
      - ./back-end/.env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data2:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy

  node:
    image: node:latest
    volumes:
      - ./back-end:/app
    command: node /app/index.js
    ports:
      - "4000:4000"
    env_file:
      - ./back-end/.env
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data2: