# Étape de construction
FROM node:18 as builder

WORKDIR /app
COPY front-end/Gradely/package*.json ./
RUN npm install
COPY front-end/Gradely .

# Build avec Vite (génère dans /app/dist par défaut)
RUN npm run build

# Étape de production
FROM nginx:alpine

# On copie depuis le dossier dist de Vite
COPY --from=builder /app/dist /usr/share/nginx/html

# Configuration Nginx
COPY front-end/Gradely/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]